version:  2.1
jobs:
  append-inventory:                        # Job Name
    docker:
      - image: cimg/base:2020.01   # Base Image
    steps:
      - checkout
      - run:                        #Install AWS CLI on base docker image 
          name: Install AWS CLI 
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:                      # create inventory file and add [all] so it can receive IPs from AWS command
          name: Create inventory file
          command: |
            mkdir project
            touch inventory
            echo [all] > project/inventory

      - run:                    # Fetch the EC2 public IPS for all instances with tag project:udacity and save it in project/inventory
          name: Save servers IPs in inventory
          command: |
            aws ec2 describe-instances \
            \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> project/inventory
      # - run:
      #     name: check files name for testing
      #     command: |
      #       cd project
      #       cat inventory

      - persist_to_workspace:   #save inventory file by workspace
          root: project
          paths:
            - inventory

  print_output_file:            # Another Job to receive the inventory file and print it
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: project
      - run: 
          name: Print Inventory
          command: |
            cd project
            cat inventory

workflows:
  my_workflow:
    jobs:
      - append-inventory
      - print_output_file:
          requires:
            - append-inventory